import ScarletFang from './images/ScarletFang.jpg';
import SalamoonIsland from './images/SalamoonIsland.jpg';
import PurpleSunset from './images/PurpleSunset.jpg';
import RelaxedTiger from './images/RelaxedTiger.jpg';
import PumpkinBow from './images/PumpkinBow.jpg';
import JuicyIsland from './images/JuicyIsland.jpg';
import GoldenLagoon from './images/GoldenLagoon.jpg';
import DragonWing from './images/DragonWing.jpg';
import DragonHead from './images/DragonHead.jpg';


export default [
  {
    id: 1, 
    name: "Scarlet Fang", 
    path: "Scarlet-Fang", 
    type: "Full Service",
    maxDwellingCapacity: 6,
    weekPrice: 1500,
    islandSize: "small",
    rentalYacht: true,
    pets: false,
    top: true, 
    img: ScarletFang,
  },
  {
    id: 2, 
    name: "Salamoon Island", 
    path: "Salamoon-Island", 
    type: "Full Service",
    maxDwellingCapacity: 10,
    weekPrice: 2000,
    islandSize: "small",
    rentalYacht: true,
    pets: false,
    top: true, 
    img: SalamoonIsland,
  },
  {
    id: 3, 
    name: "Purple Sunset", 
    path: "Purple-Sunset", 
    type: "Full Service",
    maxDwellingCapacity: 8,
    weekPrice: 1000,
    islandSize: "small",
    rentalYacht: false,
    pets: false,
    top: true, 
    img: PurpleSunset,
  },
  {
    id: 4, 
    name: "Relaxed Tiger", 
    path: "Relaxed-Tiger", 
    type: "Whole Island",
    maxDwellingCapacity: 30,
    weekPrice: 1000,
    islandSize: "small",
    rentalYacht: false,
    pets: true,
    top: false, 
    img: RelaxedTiger,
  },
  {
    id: 5, 
    name: "Pumpkin Bow", 
    path: "Pumpkin-Bow", 
    type: "Full Service",
    maxDwellingCapacity: 2,
    weekPrice: 700,
    islandSize: "medium",
    rentalYacht: false,
    pets: true,
    top: false, 
    img: PumpkinBow,
  },
  {
    id: 6, 
    name: "Juicy Island", 
    path: "Juicy-Island", 
    type: "Whole Island",
    maxDwellingCapacity: 20,
    weekPrice: 900,
    islandSize: "small",
    rentalYacht: false,
    pets: true,
    top: false, 
    img: JuicyIsland,
  },
  {
    id: 7, 
    name: "Golden Lagoon", 
    path: "Golden-Lagoon", 
    type: "Full Service",
    maxDwellingCapacity: 2,
    weekPrice: 1300,
    islandSize: "medium",
    rentalYacht: false,
    pets: true,
    top: false, 
    img: GoldenLagoon,
  },
  {
    id: 8, 
    name: "Dragon Wing", 
    path: "Dragon-Wing", 
    type: "Whole Island",
    maxDwellingCapacity: 10,
    weekPrice: 700,
    islandSize: "small",
    rentalYacht: false,
    pets: true,
    top: false, 
    img: DragonWing,
  },
  {
    id: 9, 
    name: "Dragon Head", 
    path: "Dragon-Head", 
    type: "Whole Island",
    maxDwellingCapacity: 10,
    weekPrice: 800,
    islandSize: "small",
    rentalYacht: false,
    pets: true,
    top: false, 
    img: DragonHead,
  },
]